# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e80655a8316b31b58f42fab5d0e12a25d7372624ef6fd929f6782d860a682d0de9c8299c9fd971f2156d7889763c3a6f211be09dbd18dddbd5fbb1590b48910e

test:
  secret_key_base: 12e3eacc7dc9eb6a5df7b9d6b3db4de9818a99baacf3a0813113122662eefd3666eeb6e95bd7cffd9920132add8f5ff7b78febb2d2b1c2ecd7f4a94b5b608425

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
